import { ArrowRight, CheckCircle2, FileText, FlaskConical, Layers3, Plus, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { api } from '../../api/client'
import type { Executor, Handoff, ProjectDetail, PromptRevision, ProviderProfile, WritingRule } from '../../types'

export function ExperimentStage({ projectId, handoff, detail, rules, prompts, providers, run, onResults }: { projectId: string; handoff: Handoff | null; detail: ProjectDetail; rules: WritingRule[]; prompts: PromptRevision[]; providers: ProviderProfile[]; run: (action: () => Promise<unknown>, message: string) => Promise<void>; onResults: () => void }) {
  const [executor, setExecutor] = useState<Executor>('external')
  const [provider, setProvider] = useState(providers.find((item) => item.active)?.id ?? '')
  const generationPrompts = prompts.filter((item) => item.stage === 'generate')
  const [promptId, setPromptId] = useState(generationPrompts.find((item) => item.active)?.id ?? '')
  const [ruleName, setRuleName] = useState('短内容写作规则')
  const [ruleBody, setRuleBody] = useState('')
  const activeRule = rules.find((item) => item.active)
  const comparisonRules = useMemo(() => { const seen = new Set<string>(); return rules.filter((item) => !seen.has(item.body_hash) && Boolean(seen.add(item.body_hash))).slice(0, 5) }, [rules])
  const approved = handoff?.handoff.status === 'approved'
  const common = { executor, run: executor === 'api', rule_id: activeRule?.id, provider_profile_id: executor === 'api' ? provider || undefined : undefined, prompt_revision_id: promptId || undefined }
  const start = (mode: 'single' | 'batch' | 'compare') => run(() => mode === 'single' ? api.generate(projectId, common) : mode === 'batch' ? api.batchFive(projectId, common) : api.compareRules(projectId, { rule_ids: comparisonRules.map((item) => item.id), executor, run: executor === 'api', provider_profile_id: executor === 'api' ? provider || undefined : undefined, prompt_revision_id: promptId || undefined }), mode === 'single' ? '单篇生成实验已创建' : mode === 'batch' ? '五篇批量实验已创建' : '五规则串行实验已创建')
  return <div className="experiment-layout">
    <section className="sheet experiment-console"><div className="stage-heading"><span>04</span><div><p className="kicker">GENERATION LAB</p><h2>选择一种真实实验</h2><p>没有评分、评审或自动融合。你只比较模型第一次交付的原始结果，再自己决定。</p></div></div>{!approved && <div className="warning-box"><FlaskConical size={17} /><p>生成已锁定。先完成并批准当前交接，旧交接不能自动混入新实验。</p></div>}<div className="runtime-strip"><label>执行方式<select value={executor} onChange={(e) => setExecutor(e.target.value as Executor)}><option value="external">外部 Agent / Codex</option><option value="api">工作台内 API</option></select></label>{executor === 'api' && <label>模型快照<select value={provider} onChange={(e) => setProvider(e.target.value)}>{providers.map((item) => <option value={item.id} key={item.id}>{item.name} v{item.revision} · {item.model}</option>)}</select></label>}<label>生成提示词<select value={promptId} onChange={(e) => setPromptId(e.target.value)}>{generationPrompts.map((item) => <option value={item.id} key={item.id}>v{item.revision} · {item.name}</option>)}</select></label></div><div className="experiment-options"><button disabled={!approved || !activeRule || !promptId || (executor === 'api' && !provider)} onClick={() => void start('single').catch(() => undefined)}><span><FileText size={20} /></span><div><strong>单篇生成</strong><p>一次无状态调用，一篇完整成品。</p></div><ArrowRight size={17} /></button><button disabled={!approved || !activeRule || !promptId || (executor === 'api' && !provider)} onClick={() => void start('batch').catch(() => undefined)}><span><Layers3 size={20} /></span><div><strong>同规则五篇</strong><p>一次调用返回五篇，保留同一原始响应。</p></div><ArrowRight size={17} /></button><button disabled={!approved || comparisonRules.length !== 5 || !promptId || (executor === 'api' && !provider)} onClick={() => void start('compare').catch(() => undefined)}><span><Sparkles size={20} /></span><div><strong>五规则串行对比</strong><p>{comparisonRules.length}/5 个不同规则；其余输入完全固定。</p></div><ArrowRight size={17} /></button></div></section>
    <aside className="sheet rule-panel"><div className="sheet-heading"><div><p className="kicker">WRITING RULE</p><h2>写作规则版本</h2></div>{activeRule && <span className="active-badge"><CheckCircle2 size={14} />v{activeRule.revision}</span>}</div>{activeRule ? <details open><summary>{activeRule.name}</summary><pre>{activeRule.body}</pre></details> : <div className="empty-mini">尚未建立写作规则</div>}<details className="new-rule"><summary><Plus size={14} />新增规则版本</summary><div className="details-form"><label>规则名称<input value={ruleName} onChange={(e) => setRuleName(e.target.value)} /></label><label>规则正文<textarea rows={9} value={ruleBody} onChange={(e) => setRuleBody(e.target.value)} /></label><button className="button secondary full" disabled={!ruleName.trim() || !ruleBody.trim()} onClick={() => void run(async () => { await api.addRule({ name: ruleName, body: ruleBody, activate: true }); setRuleBody('') }, '写作规则新版本已启用').catch(() => undefined)}>保存并启用</button></div></details><div className="rule-history">{rules.slice(0, 8).map((item) => <button className={item.active ? 'active' : ''} key={item.id} onClick={() => void run(() => api.activateRule(item.id), '写作规则已切换').catch(() => undefined)}><span>v{item.revision}</span><strong>{item.name}</strong><small>{item.body_hash.slice(0, 8)}</small></button>)}</div></aside>
    <section className="sheet experiment-history"><div className="sheet-heading"><div><p className="kicker">RUN HISTORY</p><h2>实验记录</h2></div><button className="button ghost" disabled={!detail.experiments.length} onClick={onResults}>查看全部结果<ArrowRight size={15} /></button></div><div className="experiment-table">{detail.experiments.map((item) => <article key={item.id}><span className={`job-state ${item.status}`} /><div><strong>{item.kind === 'single' ? '单篇生成' : item.kind === 'batch_five' ? '同规则五篇' : '五规则对比'}</strong><small>{new Date(item.created_at).toLocaleString()} · {item.executor === 'api' ? '内置 API' : '外部执行'}</small></div><em>{item.status === 'completed' ? '已完成' : item.status === 'failed' ? '失败' : '运行中'}</em><code>{item.fixed_input_hash.slice(0, 10)}</code></article>)}</div></section>
  </div>
}
