import { ArrowRight, CircleAlert, Clock3, ExternalLink, Play, RotateCcw } from 'lucide-react'
import { useMemo, useState } from 'react'
import { api } from '../../api/client'
import type { Executor, ProjectDetail, PromptRevision, ProviderProfile } from '../../types'

export function PreparationStage({ detail, prompts, providers, run, onContinue }: { detail: ProjectDetail; prompts: PromptRevision[]; providers: ProviderProfile[]; run: (action: () => Promise<unknown>, message: string) => Promise<void>; onContinue: () => void }) {
  const [executor, setExecutor] = useState<Executor>('external')
  const preparePrompts = prompts.filter((item) => item.stage === 'prepare_material')
  const referencePrompts = prompts.filter((item) => item.stage === 'select_references')
  const [preparePrompt, setPreparePrompt] = useState(preparePrompts.find((item) => item.active)?.id ?? '')
  const [referencePrompt, setReferencePrompt] = useState(referencePrompts.find((item) => item.active)?.id ?? '')
  const [provider, setProvider] = useState(providers.find((item) => item.active)?.id ?? '')
  const jobs = useMemo(() => detail.jobs.filter((job) => job.kind !== 'generate').slice().reverse(), [detail.jobs])
  const current = jobs[0]
  const finished = current?.kind === 'select_references' && current.status === 'succeeded'
  const start = () => run(() => api.prepare(detail.project.id, { executor, run: executor === 'api', prepare_prompt_id: preparePrompt || undefined, reference_prompt_id: referencePrompt || undefined, provider_profile_id: executor === 'api' ? provider || undefined : undefined }), executor === 'api' ? '准备任务已交给后台运行' : '外部准备任务已创建')
  return <div className="stage-layout">
    <section className="sheet stage-main"><div className="stage-heading"><span>02</span><div><p className="kicker">PREPARE & SELECT</p><h2>准备正式交接</h2><p>先净化材料，再只按写作技巧选择案例与钩子。两个阶段使用各自锁定的提示词版本。</p></div></div><div className="form-grid two"><label>执行方式<select value={executor} onChange={(e) => setExecutor(e.target.value as Executor)}><option value="external">外部 Agent / Codex</option><option value="api">工作台内 API</option></select></label>{executor === 'api' && <label>模型配置<select value={provider} onChange={(e) => setProvider(e.target.value)}><option value="">选择当前配置</option>{providers.map((item) => <option key={item.id} value={item.id}>{item.name} · v{item.revision} · {item.model}</option>)}</select></label>}<label>材料净化提示词<select value={preparePrompt} onChange={(e) => setPreparePrompt(e.target.value)}>{preparePrompts.map((item) => <option value={item.id} key={item.id}>v{item.revision} · {item.name}</option>)}</select></label><label>参考选择提示词<select value={referencePrompt} onChange={(e) => setReferencePrompt(e.target.value)}>{referencePrompts.map((item) => <option value={item.id} key={item.id}>v{item.revision} · {item.name}</option>)}</select></label></div>{executor === 'external' && <div className="external-callout"><ExternalLink size={18} /><div><strong>外部任务会进入原子租约队列</strong><p>在另一个终端运行 <code>inkflow job next --json</code> 领取任务，按返回的 JSON Schema 提交结果。一次只能有一个外部任务在执行。</p></div></div>}<div className="sheet-actions"><p>{detail.sources.length} 份素材将进入准备阶段。</p><button className="button primary" disabled={!preparePrompt || !referencePrompt || (executor === 'api' && !provider)} onClick={() => void start().catch(() => undefined)}><Play size={16} />开始准备</button></div></section>
    <aside className="sheet stage-side"><div className="sheet-heading"><div><p className="kicker">JOB TIMELINE</p><h2>任务记录</h2></div>{finished && <button className="button ghost" onClick={onContinue}>审阅交接<ArrowRight size={15} /></button>}</div><div className="job-list">{jobs.map((job) => { const attempt = job.attempts.at(-1); const retryable = job.status === 'failed' || job.status === 'leased'; return <article key={job.id}><header><span className={`job-state ${job.status}`} /> <div><strong>{job.kind === 'prepare_material' ? '净化材料' : '选择参考'}</strong><small>{job.executor === 'api' ? '内置 API' : '外部执行'} · {new Date(job.created_at).toLocaleString()}</small></div><em>{stateLabel(job.status)}</em></header>{attempt?.error && <div className="job-error"><CircleAlert size={15} /><span>{attempt.format_error || attempt.error}</span></div>}{attempt?.raw_response && attempt.format_error && <details><summary>查看原始返回</summary><pre>{attempt.raw_response}</pre></details>}{retryable && <button className="button secondary small" onClick={() => void run(() => api.retryJob(job.id), job.status === 'leased' ? '当前租约已释放，任务已重新排队' : '失败任务已重新排队').catch(() => undefined)}><RotateCcw size={14} />{job.status === 'leased' ? '释放并重试' : '重试本次任务'}</button>}</article>})}{!jobs.length && <div className="empty-mini"><Clock3 size={21} /><p>开始后，这里会显示真实队列状态和每次尝试。</p></div>}</div></aside>
  </div>
}

function stateLabel(status: string) { return ({ waiting: '等待前序', pending: '已排队', leased: '执行中', succeeded: '已完成', failed: '失败', cancelled: '已取消' } as Record<string, string>)[status] ?? status }
