import { Check, Copy, Download, Edit3, Save } from 'lucide-react'
import { useMemo, useState } from 'react'
import { api } from '../../api/client'
import type { Experiment, Generation } from '../../types'

export function ResultsStage({ results, experiments, run }: { results: Generation[]; experiments: Experiment[]; run: (action: () => Promise<unknown>, message: string) => Promise<void> }) {
  const [experimentId, setExperimentId] = useState('all')
  const [editing, setEditing] = useState<string | null>(null)
  const [draft, setDraft] = useState('')
  const visible = useMemo(() => experimentId === 'all' ? results : results.filter((item) => item.experiment_id === experimentId), [results, experimentId])
  const handoffCount = new Set(visible.map((item) => item.handoff_id)).size
  const beginEdit = (item: Generation) => { setEditing(item.id); setDraft(item.current_content) }
  return <div className="results-workspace"><header className="results-toolbar"><div><p className="kicker">RESULT WORKSPACE</p><h2>并排阅读，再作选择</h2><p>模型原文永不改写；你的编辑以新修订保存，导出读取最新修订。</p></div><label>实验筛选<select value={experimentId} onChange={(e) => setExperimentId(e.target.value)}><option value="all">全部实验</option>{experiments.map((item) => <option value={item.id} key={item.id}>{item.kind} · {new Date(item.created_at).toLocaleString()}</option>)}</select></label></header>{handoffCount > 1 && <div className="warning-box"><span>!</span><p>当前结果来自 {handoffCount} 个交接版本。每张卡片都标明版本，不会把它们视为同一组实验。</p></div>}<div className="result-grid">{visible.map((item, index) => <article className={`result-card ${item.selected ? 'selected' : ''}`} key={item.id}><header><div><span>OUTPUT {String(index + 1).padStart(2, '0')}</span><strong>{item.writing_rule.name} · v{item.writing_rule.revision}</strong></div>{item.selected && <span className="selected-mark"><Check size={14} />已选</span>}</header><div className="result-context"><span>交接 {item.handoff_id.split('-').at(-1)?.slice(0, 7)}</span><span>{item.edit_revision ? `人工修订 v${item.edit_revision}` : '模型原文'}</span></div>{editing === item.id ? <textarea className="result-editor" value={draft} onChange={(e) => setDraft(e.target.value)} /> : <div className="result-body">{item.current_content}</div>}<footer><div><button title="复制" onClick={() => void navigator.clipboard.writeText(item.current_content)}><Copy size={15} /></button><a title="导出 Markdown" href={api.exportUrl(item.id)}><Download size={15} /></a><button title="编辑" onClick={() => beginEdit(item)}><Edit3 size={15} /></button></div>{editing === item.id ? <button className="button primary small" disabled={!draft.trim()} onClick={() => void run(async () => { await api.editResult(item.id, draft); setEditing(null) }, '人工修订已保存').catch(() => undefined)}><Save size={14} />保存修订</button> : <button className="button secondary small" onClick={() => void run(() => api.selectResult(item.id), '已标记为选中结果').catch(() => undefined)}>{item.selected ? '保持选中' : '选中结果'}</button>}</footer><details className="result-metadata"><summary>查看本次完整输入与运行快照</summary><div><h4>写作规则</h4><pre>{item.writing_rule.body}</pre><h4>模型配置</h4><pre>{JSON.stringify(item.provider_snapshot, null, 2) || '外部执行'}</pre><h4>提示词快照</h4><pre>{JSON.stringify(item.prompt_snapshot, null, 2)}</pre><h4>执行元数据</h4><pre>{JSON.stringify(item.executor_metadata, null, 2)}</pre></div></details></article>)}</div>{!visible.length && <div className="empty-state wide"><Edit3 size={28} /><h3>还没有生成结果</h3><p>完成一个单篇、批量或规则对比实验后，原始成品会出现在这里。</p></div>}</div>
}
